include ../../base/sw/base_include_aal.mk

CFLAGS += -DVCMAP_ENABLE_DEFAULT=false

all: test_mem_perf_aal test_mem_latency_aal compute_latency_qos_params_aal compute_vc_map_params_aal

test_mem_perf_aal: test_mem_perf.o test_mem_perf_common.o $(BASE_FILE_OBJ)
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

test_mem_latency_aal: test_mem_latency.o test_mem_perf_common.o $(BASE_FILE_OBJ)
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

compute_latency_qos_params_aal: compute_latency_qos_params.o test_mem_perf_common.o $(BASE_FILE_OBJ)
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

compute_vc_map_params_aal: compute_vc_map_params.o test_mem_perf_common.o $(BASE_FILE_OBJ)
	$(CXX) $(CFLAGS) -o $@ $^ $(LDFLAGS)

.cpp.o: cci_test.h $(BASE_FILE_INC)
	$(CXX) $(CPPFLAGS) $(CFLAGS) -DUSE_LEGACY_AAL -c -o $@ $<

clean:
	$(RM) test_mem_perf_aal test_mem_latency_aal compute_latency_qos_params_aal compute_vc_map_params_aal $(BASE_FILE_OBJ) *.o

.PHONY:all clean
