// req_C1TxRAM2PORT.v

// Generated using ACDS version 17.1.1 249

`timescale 1 ps / 1 ps
module req_C1TxRAM2PORT (
		input  wire [555:0] data,      //  ram_input.datain
		input  wire [8:0]   wraddress, //           .wraddress
		input  wire [8:0]   rdaddress, //           .rdaddress
		input  wire         wren,      //           .wren
		input  wire         clock,     //           .clock
		output wire [555:0] q          // ram_output.dataout
	);

	req_C1TxRAM2PORT_ram_2port_171_sku4qca ram_2port_0 (
		.data      (data),      //   input,  width = 556,  ram_input.datain
		.wraddress (wraddress), //   input,    width = 9,           .wraddress
		.rdaddress (rdaddress), //   input,    width = 9,           .rdaddress
		.wren      (wren),      //   input,    width = 1,           .wren
		.clock     (clock),     //   input,    width = 1,           .clock
		.q         (q)          //  output,  width = 556, ram_output.dataout
	);

endmodule
