include ../../../bcommon/common.mk

AFU.PLATFORMS := dcp_1.0-rc dcp_1.0-insp dcp_2.0-sp dcp_2.0-dc_es dcp_2.0-dc
AFU.NAME := nlb
AFU.VARIANTS := mode_0 mode_3 mode_0_stp

include ../../../bcommon/afu.mk
