//
// Generated by afu_json_mgr from ../hw/rtl/e100g_mac_afu.json
//

#ifndef __AFU_JSON_INFO__
#define __AFU_JSON_INFO__

#define AFU_ACCEL_NAME "e100g_mac_afu"
#define AFU_ACCEL_UUID "C44CD6FE-9829-44FE-840B-4A2E16C24185"
#define AFU_IMAGE_POWER 0
#define AFU_TOP_IFC "ccip_std_afu"

#endif // __AFU_JSON_INFO__
