// (C) 2001-2018 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Copyright 2014 Altera Corporation. All rights reserved.
// Altera products are protected under numerous U.S. and foreign patents, 
// maskwork rights, copyrights and other intellectual property laws.  
//
// This reference design file, and your use thereof, is subject to and governed
// by the terms and conditions of the applicable Altera Reference Design 
// License Agreement (either as signed by you or found at www.altera.com).  By
// using this reference design file, you indicate your acceptance of such terms
// and conditions between you and Altera Corporation.  In the event that you do
// not agree with such terms and conditions, you may not use the reference 
// design file and please promptly destroy any copies you have made.
//
// This reference design file is being provided on an "as-is" basis and as an 
// accommodation and therefore all warranties, representations or guarantees of 
// any kind (whether express, implied or statutory) including, without 
// limitation, warranties of merchantability, non-infringement, or fitness for
// a particular purpose, are specifically disclaimed.  By making this reference
// design file available, Altera expressly does not recommend, suggest or 
// require that this reference design file be used in combination with any 
// other product not provided by Altera.
/////////////////////////////////////////////////////////////////////////////


`timescale 1ps/1ps

// DESCRIPTION
// MLAB based synchronizer of width 20.
// Generated by one of Gregg's toys.   Share And Enjoy.

module alt_e100s10_sync20m #(
    parameter SIM_EMULATE = 1'b0
) (
    input din_clk,
    input [19:0] din,
    input dout_clk,
    output [19:0] dout
);

wire [19:0] dout_w;
alt_e100s10_mlab20a1r1w1 m0 (
    .rclk(dout_clk),
    .wclk(din_clk),
    .waddr(1'b0),
    .din(din),
    .raddr(1'b0),
    .dout(dout_w)
);
defparam m0 .SIM_EMULATE = SIM_EMULATE;


generate
genvar i;
for (i=0; i<20; i=i+1)
begin : sync
       alt_e100s10_altera_std_synchronizer_nocut #(
                    .DEPTH(2),
                    .RST_VALUE(20'b0)
            )  synchronizer_nocut_inst  (
                    .clk(dout_clk),
                    .reset_n(1'b1),
                    .din(dout_w[i]),
                    .dout(dout[i])
       );
end
endgenerate


endmodule

